---
abstract: 'Learn how to start using Elastic Search with perl for your apps'
author:
  - 'Hernan Lopes (hernanlopes@gmail.com)'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120630'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tutorial-Elastic-Search-With-Perl-First-Steps-Cheat-Sheet
no_index:
  directory:
    - t
    - inc
requires:
  Data::Printer: 0
  ElasticSearch: 0
  File::Slurp: 0
  Moose: 0
  Test::Simple: 0.44
  Try::Tiny: 0
version: 0.02
